import tempfile
import unittest
from pathlib import Path

from mapwright.ingest import (
    detect_encoding,
    detect_header_line,
    parse_text,
    read_source,
)


class EncodingTest(unittest.TestCase):
    def test_utf8(self):
        self.assertEqual(detect_encoding("اسم,id\n".encode("utf-8")), "utf-8")

    def test_byte_order_mark(self):
        self.assertEqual(detect_encoding(b"\xef\xbb\xbfa,b\n"), "utf-8-sig")

    def test_windows_1256(self):
        self.assertEqual(detect_encoding("ريال,SAR\n".encode("cp1256")), "cp1256")


class HeaderTest(unittest.TestCase):
    def test_title_rows_above_header_are_skipped(self):
        lines = [["Sales Orders Export"], ["Generated by Finance"], ["id", "amount"], ["1", "5"], ["2", "6"]]
        self.assertEqual(detect_header_line(lines), 3)

    def test_header_on_first_line(self):
        self.assertEqual(detect_header_line([["id", "amount"], ["1", "5"]]), 1)


class ParseTextTest(unittest.TestCase):
    def test_values_stay_text_and_rows_are_numbered_after_header(self):
        table = parse_text("Title\nid,amount\n001, 5.0 \n\n002,6\n")
        self.assertEqual(table.header, ["id", "amount"])
        self.assertEqual(table.header_line, 2)
        self.assertEqual(table.rows[0], {"id": "001", "amount": " 5.0 "})
        self.assertEqual(table.row_numbers, [1, 3])

    def test_semicolon_delimiter(self):
        table = parse_text("id;name\n1;Sara\n2;Ali\n")
        self.assertEqual(table.delimiter, ";")
        self.assertEqual(table.column("name"), ["Sara", "Ali"])

    def test_short_rows_are_padded_and_duplicate_headers_renamed(self):
        table = parse_text("a,a,b\n1,2\n3,4,5\n")
        self.assertEqual(table.header, ["a", "a_2", "b"])
        self.assertEqual(table.rows[0], {"a": "1", "a_2": "2", "b": ""})

    def test_header_text_is_kept_exactly(self):
        table = parse_text("CompanyName, CompanyNumber\nACME LTD,0001\n")
        self.assertEqual(table.header, ["CompanyName", " CompanyNumber"])
        self.assertEqual(table.rows[0][" CompanyNumber"], "0001")

    def test_read_source_detects_windows_1256(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "export.csv"
            path.write_bytes("Report\nid,currency\n1,ريال\n2,SAR\n".encode("cp1256"))
            table = read_source(path)
        self.assertEqual(table.encoding, "cp1256")
        self.assertEqual(table.header_line, 2)
        self.assertEqual(table.column("currency"), ["ريال", "SAR"])
        self.assertEqual(table.settings(), {"encoding": "cp1256", "delimiter": ",", "header_line": 2})


if __name__ == "__main__":
    unittest.main()
